version: "3.9"
   
services:
  db:
    image: postgres:15.2
    container_name: hairdresserapp_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"

  web:
    image: hairdresserapp:0.1
    container_name: hairdresserapp_web
    hostname: hairdresserapp_web
    #command: python manage.py runserver 0.0.0.0:80
    #command: django-admin startproject hairdresser
    #command: django-admin startapp hairdresserapp ##Inicializacion de proyecto
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - ./code/hairdresser/:/code/:rw
      - .vscode-container/:/root/.vscode-server/:rw
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  # data-storage:
  #   image: nginx
  #   hostname: data-storage
  #   container_name: data-storage
  #   restart: unless-stopped
  #   volumes:
  #     - ./code:/code
  #     - "./data-storage/data:/home/data-storage/:ro"
  #     - "./data-storage/etc_nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
  #   ports:
  #     - "0.0.0.0:8000:8000"
  #   logging:
  #       driver: "json-file"
  #       options:
  #         max-size: "100m"
  #         max-file: "3" 