version: "3.9"
   
services:
  db:
    image: mariadb:10.11
    container_name: hairdresserapp_db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=h4irdress3rapp
      - MARIADB_DATABASE=hairdresserapp
      - MARIADB_USER=hairdresserapp
      - MARIADB_PASSWORD=postgres
    volumes:
      - ./mariadb/var_lib_mysql/:/var/lib/mysql/:rw
#    ports:
#      - "0.0.0.0:5432:3306"

  web:
    image: hairdresserapp:1.2
    container_name: hairdresserapp_web
    hostname: hairdresserapp_web
    restart: unless-stopped
    ports:
      - "0.0.0.0:8000:80"
#    volumes:
#      - ./code/hairdresser/:/code/:rw
    depends_on:
      - db
