# Generated by Django 4.2 on 2023-05-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_oferta_updated_roles_created_roles_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='oferta',
        ),
    ]
