# Generated by Django 4.2 on 2023-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_servicio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='oferta',
            field=models.ManyToManyField(to='gestion.oferta'),
        ),
    ]
