# Generated by Django 4.2 on 2023-05-15 13:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_servicio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='movil',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
