# Generated by Django 4.2 on 2023-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_usuario_last_login_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='passwd',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
