# Generated by Django 4.2 on 2023-05-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_usuario_passwd_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
